Add missing --version_cc to the custom `mariadb_config` (Closes: #1146585)
Upstream MariaDB Connector/C's compiled mariadb_config has this option:

  $ ./usr/bin/mariadb_config --help
  Copyright 2011-2020 MariaDB Corporation AB
  Get compiler flags for using the MariaDB Connector/C.
  [...]
    --version       [11.8.8]
    --cc_version    [3.4.9]

When this was replaced by an architecture-independent shell script in
Debian in 0e01b12d6f32 this `--cc_version` was omitted, probably by
oversight.

However, e.g. MariaDB Connector/Python (the "mariadb" distribution on
PyPI, MariaDB's officially supported Python driver, not packaged in
Debian) calls exactly this option during its build to verify Connector/C
>= 3.3.1.

This change fixes the build error in the "mariadb" Python library:

  File ".../mariadb_posix.py", line 63, in get_config
    if version.Version(cc_version[0]) < version.Version(required_version):
  IndexError: list index out of range