WIP: Add missing MARIADB_OPT_FOLLOW_INSTANT_FAILOVERS
/tmp/build/source/client/mysql.cc:1507:23: error: ‘MARIADB_OPT_FOLLOW_INSTANT_FAILOVERS’ was not declared in this scope
 1507 |   mysql_options(mysql,MARIADB_OPT_FOLLOW_INSTANT_FAILOVERS,
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~