Normalize two Aria variables in configuration tracing autopkgtest
Starting on March 16, 2026, the configuratin-tracing autopkgtest started
failing with the error below. The new values are actually aligned with
upstream documentation on what the default should be, so switch to using
them, but normaize the values to avoid older Ubuntu and Debian versions
from having the test fail.

The root cause why it changed now and why all this time the defaults
have been zero and empty is unknown.

    autopkgtest [08:07:55]: test configuration-tracing: [-----------------------
    ...
    Tracing: /usr/sbin/mariadbd --verbose --help
    2026-03-16  8:07:55 0 [Warning] Could not open mysql.plugin table: "Table 'mysql.plugin' doesn't exist". Some options may be missing from the help text
    diff --ignore-space-change -u mariadbd-verbose-help.expected mariadbd-verbose-help.actual
    --- mariadbd-verbose-help.expected	2026-03-16 01:01:00.000000000 +0000
    +++ mariadbd-verbose-help.actual	2026-03-16 08:07:55.640798692 +0000
    @@ -2523,7 +2523,7 @@
     analyze-max-length                                           4294967295
     analyze-sample-percentage                                    100
     aria-block-size                                              8192
    -aria-checkpoint-interval                                     0
    +aria-checkpoint-interval                                     30
     aria-checkpoint-log-activity                                 1048576
     aria-encrypt-tables                                          FALSE
     aria-force-start-after-recovery-failures                     0
    @@ -2538,7 +2538,7 @@
     aria-pagecache-buffer-size                                   134217728
     aria-pagecache-division-limit                                100
     aria-pagecache-file-hash-size                                512
    -aria-recover-options
    +aria-recover-options                                         BACKUP,QUICK
     aria-repair-threads                                          1
     aria-sort-buffer-size                                        268434432
     aria-stats-method                                            nulls_unequal
    Error: Output from '/usr/sbin/mariadbd --verbose --help' did NOT match what was expected