Make hurd-i386 build fully pass (Closes: #1069094)
- Install mariadb.service on Linux only
- Change dh_missing from fail to list on non-Linux
- Disks plugin: Define PATH_MAX if not defined
- Connect: Add Hurd to define __USE_FILE_OFFSET64 et al

Additionally the file debian/unstable-tests.hurd-i386 should be linked
to unstable-tests.hurd (or equivalent, and later also to -amd64)
since dpkg-architecture -qDEB_BUILD_ARCH results in hurd-i386.

Unfortunately the build will still fail after these changes as the
post-build MTR test still errors with:

    [Note] Plugin 'INNODB_SYS_VIRTUAL' is disabled.
    ERROR: 1017  Can't find file: '(temporary)'
    (errno: 1073741826 "No such file or directory")
    [ERROR] Aborting

These MTR errors however can be dealt with later separately after these
changes ensures that the build passes.